global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'kafka-exporter'
    static_configs:
      - targets: ['kafka-exporter:9308']

  - job_name: 'stream-processor'
    static_configs:
      - targets: ['stream-processor:8000']
    metrics_path: '/metrics'

  - job_name: 'news2-api'
    static_configs:
      - targets: ['news2-api:8080']
    metrics_path: '/metrics'